package com.company.GUI.Manager;

import com.company.Currency.Currency;
import com.company.Factories.PersonFactory;
import com.company.GUI.MyPage;
import com.company.GUI.PageManager;
import com.company.Persons.Customer;
import com.company.Persons.Manager;
import com.company.Stock.StockMarket;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.List;

/**
 * Class of page for viewing debtors
 */
public class PageDebtors implements MyPage {
    private JPanel rootPanel;
    private JLabel lbTitle;
    private JScrollPane sp;
    private JTable tbDebtors;
    private JButton btCancel;

    /**
     * Constructor
     * @param currency Holds Forex info for the day
     * @param stockMarket Holds stock info for the day
     * @throws IOException Ensures proper file parsing
     */
    public PageDebtors(Manager manager, Currency currency, StockMarket stockMarket) {
        PersonFactory personFactory = new PersonFactory();
        List<Customer> debtors = personFactory.getCustomersWithLoan();
        tbDebtors.setModel(new DefaultTableModel(
                null,
                new String[]{"Customer ID", "Name"}
        ));
        DefaultTableModel model = (DefaultTableModel) tbDebtors.getModel();
        for (Customer debtor : debtors) {
            model.addRow(new Object[]{debtor.getId(), debtor.getName()});
        }
        btCancel.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                PageManager.backToOldPage();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        lbTitle = new JLabel();
        lbTitle.setText("View Debtors");
        rootPanel.add(lbTitle, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        sp = new JScrollPane();
        rootPanel.add(sp, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        tbDebtors = new JTable();
        sp.setViewportView(tbDebtors);
        btCancel = new JButton();
        btCancel.setText("Cancel");
        rootPanel.add(btCancel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

    /**
     * Method for getting root panel
     *
     * @return root panel
     */
    @Override
    public JPanel getRootPanel() {
        return rootPanel;
    }
}
